name: Continous Training
on:
  workflow_dispatch:
    input:
      reason:
        description: 'Why to run this?'
        required: false
        default: running CT
permissions:
  id-token: write # need this for OIDC  
  contents: write
  pull-requests: write 
  issues: read
  packages: none
jobs:
  continous-training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::949327828011:role/s3-dvc
          role-session-name: api-testing
          aws-region: us-east-1
      - name: Train model
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r src/requirements.txt
          dvc pull model/model.pkl -r model-tracker
          dvc unprotect model/model.pkl
          dvc repro -f
          echo "Training completed"
          dvc add model/model.pkl -r model-tracker --to-remote
          dvc push model/model.pkl.dvc -r model-tracker
      - name: commit .dvc file changes
        run: |
          git config --global user.email "santiagoprado12@gmail.com"
          git config --global user.name "github-actions[bot]"
          git add model/model.pkl.dvc
          git commit -m "Updating model serialization"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{github.ref}}
      - name: Set up Node 16
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: iterative/setup-cml@v1
      - name: Push metrics
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Used for github pages
        run: |
          cat report.txt >> report.md 
          echo "![](./prediction_behavior.png)" >> report.md
          cml comment create report.md
  
