name: Testing API
on: [push, pull_request]

permissions:
  id-token: write # need this for OIDC  
  contents: read

jobs:
  testing-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::949327828011:role/s3-dvc
          role-session-name: api-testing
          aws-region: us-east-1
      - name: Creating and activatin virtual environment
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
      - name: Installing dependencies
        run: |
          pip3 install dvc[s3]
          pip3 install -r requirements_test.txt
      - name: Test api
        run: |
          dvc pull model/model.pkl -r model-tracker
          pytest tests.py
      